export const Sniper_New = {
    network: "",
    contract: "",
    autobuy: false,
    buyamount: "0",
    gasprice: "1", 
    priority: "0.1",
    slippage: "0",
    smartslip: false,
    wallet: 0,
    result: "",
    multi: false,
    blockwait: 0,
    startprice: 10000,
    sellrate: 1000,
    autosell: false,
    sold: false,
    private: false,
    token: {
        name: "",
        symbol: "",
        decimal: "",
        supply: "",
        owner: "",
        lppair: "",
        honeypot: 0,
        buytax: 0,
        selltax: 0,
        transferfee: 0,
        maxwallet: "",
        maxwp: 0,
        methods: []
    }
}